version: '3'
services:
  api:
    build: ./api
    ports:
      - 8000:5000
    depends_on:
      - postgres
    restart: always
  postgres:
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres
    restart: always
  web:
    build: ./web
    ports:
      - 80:80
    restart: always
