version: '3'
services:
  api:
    build: ./api
    ports:
      - 8000:5000
    depends_on:
      - postgres
    volumes:
      - ./api/src:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
  postgres:
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    image: postgres
  web:
    build: ./web
    ports:
      - 8080:80
    volumes:
      - ./web/dist:/usr/share/nginx/html
